/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareYourStoryRouteImport } from './routes/share-your-story'
import { Route as DonateThankYouRouteImport } from './routes/donate.thank-you'
import { Route as StoriesTanjaClaraRouteImport } from './routes/stories.tanja-clara'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYourStoryRoute = ShareYourStoryRouteImport.update({
  id: '/share-your-story',
  path: '/share-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateThankYouRoute = DonateThankYouRouteImport.update({
  id: '/donate/thank-you',
  path: '/donate/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesTanjaClaraRoute = StoriesTanjaClaraRouteImport.update({
  id: '/stories/tanja-clara',
  path: '/stories/tanja-clara',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/donate/thank-you': typeof DonateThankYouRoute
  '/stories/tanja-clara': typeof StoriesTanjaClaraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/donate/thank-you': typeof DonateThankYouRoute
  '/stories/tanja-clara': typeof StoriesTanjaClaraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/donate/thank-you': typeof DonateThankYouRoute
  '/stories/tanja-clara': typeof StoriesTanjaClaraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/share-your-story' | '/donate/thank-you' | '/stories/tanja-clara'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share-your-story' | '/donate/thank-you' | '/stories/tanja-clara'
  id:
    | '__root__'
    | '/'
    | '/share-your-story'
    | '/donate/thank-you'
    | '/stories/tanja-clara'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareYourStoryRoute: typeof ShareYourStoryRoute
  DonateThankYouRoute: typeof DonateThankYouRoute
  StoriesTanjaClaraRoute: typeof StoriesTanjaClaraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-your-story': {
      id: '/share-your-story'
      path: '/share-your-story'
      fullPath: '/share-your-story'
      preLoaderRoute: typeof ShareYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/thank-you': {
      id: '/donate/thank-you'
      path: '/donate/thank-you'
      fullPath: '/donate/thank-you'
      preLoaderRoute: typeof DonateThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/tanja-clara': {
      id: '/stories/tanja-clara'
      path: '/stories/tanja-clara'
      fullPath: '/stories/tanja-clara'
      preLoaderRoute: typeof StoriesTanjaClaraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareYourStoryRoute: ShareYourStoryRoute,
  DonateThankYouRoute: DonateThankYouRoute,
  StoriesTanjaClaraRoute: StoriesTanjaClaraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
